#!/usr/bin/env bash
# Sync .ai/rules/*.mdc into agent-native locations.
#
# Background: Claude Code, Codex, and Gemini only natively load a single
# project-root instructions file (AGENTS.md / CLAUDE.md / GEMINI.md). They do
# NOT read .claude/rules/, .codex/rules/, or .gemini/rules/, and they do NOT
# reliably honour "read this path" directives in the root file. Cursor is
# different — it natively loads .cursor/rules/*.mdc with frontmatter-aware
# `alwaysApply` / `globs` semantics.
#
# So this script:
#   1. Ensures every .ai/rules/*.mdc has a .cursor/rules/<same>.mdc symlink.
#   2. Renders every .ai/rules/*.mdc body into AGENTS.md between fenced markers,
#      so the harnesses that can only load one root file get the content.
#
# Idempotent. Run after editing any rule. Wire into pre-commit via lefthook
# (see lefthook.agent-rules.yml fragment).
#
# Usage:
#   ./scripts/sync-agent-rules.sh              # sync in place
#   ./scripts/sync-agent-rules.sh --check      # exit 1 if rules are stale (drift guard)
#   ./scripts/sync-agent-rules.sh --no-cursor  # skip .cursor/rules (project doesn't use Cursor)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RULES_DIR="$ROOT/.ai/rules"
AGENTS_MD="$ROOT/AGENTS.md"
CURSOR_RULES_DIR="$ROOT/.cursor/rules"

BEGIN_MARKER='<!-- BEGIN: project rules (auto-generated from .ai/rules/) -->'
END_MARKER='<!-- END: project rules -->'

MODE="sync"
CURSOR=true
for arg in "$@"; do
    case "$arg" in
        --check) MODE="check" ;;
        --no-cursor) CURSOR=false ;;  # project doesn't use Cursor — skip its rules dir
    esac
done

if [[ ! -d "$RULES_DIR" ]]; then
    echo "error: $RULES_DIR not found" >&2
    exit 1
fi

# ── 1. Ensure Cursor symlinks ──────────────────────────────────────────
ensure_cursor_links() {
    mkdir -p "$CURSOR_RULES_DIR"
    local added=0
    for f in "$RULES_DIR"/*.mdc; do
        [[ -f "$f" ]] || continue
        local name link target
        name="$(basename "$f")"
        link="$CURSOR_RULES_DIR/$name"
        target="../../.ai/rules/$name"

        if [[ -L "$link" ]] && [[ "$(readlink "$link")" == "$target" ]]; then
            continue
        fi

        if [[ "$MODE" == "check" ]]; then
            echo "drift: missing cursor symlink for $name" >&2
            exit 1
        fi

        ln -sf "$target" "$link"
        added=$((added + 1))
    done

    # Prune dangling symlinks (rule removed from .ai/rules but symlink lingered)
    local pruned=0
    for link in "$CURSOR_RULES_DIR"/*.mdc; do
        [[ -L "$link" ]] || continue
        local target
        target="$(readlink "$link")"
        if [[ ! -e "$CURSOR_RULES_DIR/$target" ]]; then
            if [[ "$MODE" == "check" ]]; then
                echo "drift: dangling cursor symlink $(basename "$link")" >&2
                exit 1
            fi
            rm "$link"
            pruned=$((pruned + 1))
        fi
    done

    if [[ "$MODE" == "sync" ]] && [[ $((added + pruned)) -gt 0 ]]; then
        echo "  cursor: +$added new, -$pruned pruned"
    fi
}

# ── 2. Build the rendered block from .ai/rules/*.mdc bodies ────────────────
build_rules_block() {
    local out="$1"
    {
        printf '%s\n' "$BEGIN_MARKER"
        printf '\n'
        printf '## Project Coding Rules\n\n'
        printf '> Auto-generated by `scripts/sync-agent-rules.sh` from `.ai/rules/*.mdc`.\n'
        printf '> **Edit the source files, not this block** — changes here are overwritten on next sync.\n>\n'
        printf '> Cursor loads `.cursor/rules/*.mdc` natively with its own glob/alwaysApply\n'
        printf '> semantics. Claude Code, Codex, and Gemini only load this file, so all\n'
        printf '> rules are inlined here for reliable delivery.\n\n'

        for f in "$RULES_DIR"/*.mdc; do
            [[ -f "$f" ]] || continue
            local name
            name="$(basename "$f" .mdc)"
            printf '### `%s`\n\n' "$name"
            # Strip frontmatter (everything between the first two `---` lines).
            # If no frontmatter exists, emit everything.
            awk '
                BEGIN { in_fm = 0; fm_done = 0 }
                NR == 1 && /^---$/ { in_fm = 1; next }
                in_fm && /^---$/ { in_fm = 0; fm_done = 1; next }
                in_fm { next }
                { print }
            ' "$f"
            printf '\n'
        done

        printf '%s\n' "$END_MARKER"
    } > "$out"
}

# ── 3. Replace block in AGENTS.md (or append if markers missing) ────────
sync_agents_md() {
    local rendered
    rendered="$(mktemp)"
    build_rules_block "$rendered"

    if [[ ! -f "$AGENTS_MD" ]]; then
        echo "error: $AGENTS_MD not found — create it before running sync" >&2
        rm "$rendered"
        exit 1
    fi

    local new_md
    new_md="$(mktemp)"

    if grep -qF "$BEGIN_MARKER" "$AGENTS_MD"; then
        # Replace in place between markers.
        awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v rendered="$rendered" '
            $0 == begin {
                while ((getline line < rendered) > 0) print line
                close(rendered)
                skip = 1
                next
            }
            $0 == end {
                skip = 0
                next
            }
            !skip
        ' "$AGENTS_MD" > "$new_md"
    else
        # No markers yet — append the rendered block at the end.
        cat "$AGENTS_MD" > "$new_md"
        printf '\n---\n\n' >> "$new_md"
        cat "$rendered" >> "$new_md"
    fi

    local count
    count=$(find "$RULES_DIR" -maxdepth 1 -name '*.mdc' | wc -l | tr -d ' ')

    if [[ "$MODE" == "check" ]]; then
        if ! cmp -s "$AGENTS_MD" "$new_md"; then
            echo "drift: AGENTS.md rendered rules block is stale" >&2
            echo "fix:   scripts/sync-agent-rules.sh" >&2
            rm "$rendered" "$new_md"
            exit 1
        fi
    else
        if cmp -s "$AGENTS_MD" "$new_md"; then
            echo "  agents.md: $count rules already current"
        else
            mv "$new_md" "$AGENTS_MD"
            echo "  agents.md: rendered $count rules"
        fi
    fi

    rm -f "$rendered" "$new_md"
}

if [[ "$CURSOR" == true ]]; then
    ensure_cursor_links
fi
sync_agents_md

if [[ "$MODE" == "sync" ]]; then
    echo "✓ agent rules synced"
fi
