"""Idempotent .gitignore updates for scaffold-generated directories.

Faithful port of update_gitignore() from scaffold.sh.
"""

from __future__ import annotations

from pathlib import Path

_ARTIFACTS_MARKER = ".ai/artifacts/"
_TOOL_RULES_MARKER = "# Tool-specific rule symlinks"

_ARTIFACTS_BLOCK = """\

# Working files (ephemeral)
.ai/artifacts/
!.ai/artifacts/decisions/
"""

_TOOL_RULES_HEADER = "\n# Tool-specific rule symlinks (auto-generated by scaffold.sh)\n"


def update_gitignore(project_dir: Path, entries: list[str]) -> list[str]:
    """Idempotently append scaffold entries to *project_dir*/.gitignore.

    *entries* is a list of lines to add under the tool-rules section
    (e.g. [".cursor/rules/", "CODEX.md"]).  The artifacts block and the
    tool-rules section are each added only once.

    Returns a list of section names actually appended ("artifacts", "tool-rules").
    """
    gitignore = project_dir / ".gitignore"

    existing = gitignore.read_text() if gitignore.is_file() else ""

    needs_artifacts = _ARTIFACTS_MARKER not in existing
    needs_tool_rules = _TOOL_RULES_MARKER not in existing

    appended: list[str] = []

    if not needs_artifacts and not needs_tool_rules:
        return appended

    additions = "\n"  # blank separator line (mirrors bash: echo "" >> .gitignore)

    if needs_artifacts:
        additions += _ARTIFACTS_BLOCK
        appended.append("artifacts")

    if needs_tool_rules and entries:
        additions += _TOOL_RULES_HEADER
        for entry in entries:
            additions += entry + "\n"
        appended.append("tool-rules")

    gitignore.write_text(existing + additions)
    return appended
